version: '3.1'
services:
  db:
    image: postgres
    restart: always
    container_name: database-biblioteca
    environment:
      POSTGRES_USER: biblioteca
      POSTGRES_PASSWORD: biblioteca123
      POSTGRES_DB: biblioteca
    ports:
      - '5432:5432'
