version: '3.8'

services:
  db:
    container_name: database-biblioteca
    image: postgres:12-alpine
    restart: 'no'
    env_file:
      - ./.env-docker
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - '$POSTGRES_PORT:$POSTGRES_PORT'
    networks:
      - biblioteca
    volumes:
      - bibliotecadb:/var/lib/postgresql/data

  api:
    container_name: api-biblioteca
    build: .
    restart: unless-stopped
    env_file:
      - ./.env-docker
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - DATABASE_URL=$DATABASE_URL
      - PORT=$PORT
    ports:
      - '$PORT:$PORT'
    networks:
      - biblioteca
    depends_on:
      - db

networks:
  biblioteca:
    driver: bridge

volumes:
  bibliotecadb:
