version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  test:
    docker:
      - image: cimg/node:17.2.0
      - image: cimg/postgres:14.2.0

    environment:
      DATABASE_URL: "postgresql://biblioteca:biblioteca123@localhost:5432/test_biblioteca?schema=public"
      PORT: 3000

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test:migrate:ci && npm run test:ci
          name: Run tests

workflows:
  on_commit:
    jobs:
      - test
