version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  test:
    docker:
      - image: cimg/node:17.2.0

    environment:
      DATABASE_URL: 'file:./test.db'
      PORT: 3000

    steps:
      - checkout
      - run:
          command: npm run test:ci
          name: Run tests

workflows:
  on_commit:
    jobs:
      - test
